server:
  port: 8080
  servlet:
    context-path:

spring:
  data:
    rest:
      detection-strategy: annotated
      base-path: v1
  datasource:
    url: jdbc:h2:~/db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect

telegrambots:
